# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg.proto',
  package='decoderbufs',
  serialized_pb=_b('\n\tmsg.proto\x12\x0b\x64\x65\x63oderbufs\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x02(\x01\x12\t\n\x01y\x18\x02 \x02(\x01\"\x8e\x02\n\x0c\x44\x61tumMessage\x12\x13\n\x0b\x63olumn_name\x18\x01 \x01(\t\x12\x13\n\x0b\x63olumn_type\x18\x02 \x01(\x03\x12\x15\n\x0b\x64\x61tum_int32\x18\x03 \x01(\x05H\x00\x12\x15\n\x0b\x64\x61tum_int64\x18\x04 \x01(\x03H\x00\x12\x15\n\x0b\x64\x61tum_float\x18\x05 \x01(\x02H\x00\x12\x16\n\x0c\x64\x61tum_double\x18\x06 \x01(\x01H\x00\x12\x14\n\ndatum_bool\x18\x07 \x01(\x08H\x00\x12\x16\n\x0c\x64\x61tum_string\x18\x08 \x01(\tH\x00\x12\x15\n\x0b\x64\x61tum_bytes\x18\t \x01(\x0cH\x00\x12)\n\x0b\x64\x61tum_point\x18\n \x01(\x0b\x32\x12.decoderbufs.PointH\x00\x42\x07\n\x05\x64\x61tum\"4\n\x08TypeInfo\x12\x10\n\x08modifier\x18\x01 \x02(\t\x12\x16\n\x0evalue_optional\x18\x02 \x02(\x08\"\xee\x01\n\nRowMessage\x12\x16\n\x0etransaction_id\x18\x01 \x01(\r\x12\x13\n\x0b\x63ommit_time\x18\x02 \x01(\x04\x12\r\n\x05table\x18\x03 \x01(\t\x12\x1b\n\x02op\x18\x04 \x01(\x0e\x32\x0f.decoderbufs.Op\x12,\n\tnew_tuple\x18\x05 \x03(\x0b\x32\x19.decoderbufs.DatumMessage\x12,\n\told_tuple\x18\x06 \x03(\x0b\x32\x19.decoderbufs.DatumMessage\x12+\n\x0cnew_typeinfo\x18\x07 \x03(\x0b\x32\x15.decoderbufs.TypeInfo*(\n\x02Op\x12\n\n\x06INSERT\x10\x00\x12\n\n\x06UPDATE\x10\x01\x12\n\n\x06\x44\x45LETE\x10\x02\x42\x33\n&io.debezium.connector.postgresql.protoB\x07PgProtoH\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_OP = _descriptor.EnumDescriptor(
  name='Op',
  full_name='decoderbufs.Op',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INSERT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPDATE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=625,
  serialized_end=665,
)
_sym_db.RegisterEnumDescriptor(_OP)

Op = enum_type_wrapper.EnumTypeWrapper(_OP)
INSERT = 0
UPDATE = 1
DELETE = 2



_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='decoderbufs.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='decoderbufs.Point.x', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='decoderbufs.Point.y', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=55,
)


_DATUMMESSAGE = _descriptor.Descriptor(
  name='DatumMessage',
  full_name='decoderbufs.DatumMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='column_name', full_name='decoderbufs.DatumMessage.column_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='column_type', full_name='decoderbufs.DatumMessage.column_type', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='datum_int32', full_name='decoderbufs.DatumMessage.datum_int32', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='datum_int64', full_name='decoderbufs.DatumMessage.datum_int64', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='datum_float', full_name='decoderbufs.DatumMessage.datum_float', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='datum_double', full_name='decoderbufs.DatumMessage.datum_double', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='datum_bool', full_name='decoderbufs.DatumMessage.datum_bool', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='datum_string', full_name='decoderbufs.DatumMessage.datum_string', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='datum_bytes', full_name='decoderbufs.DatumMessage.datum_bytes', index=8,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='datum_point', full_name='decoderbufs.DatumMessage.datum_point', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='datum', full_name='decoderbufs.DatumMessage.datum',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=58,
  serialized_end=328,
)


_TYPEINFO = _descriptor.Descriptor(
  name='TypeInfo',
  full_name='decoderbufs.TypeInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='modifier', full_name='decoderbufs.TypeInfo.modifier', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value_optional', full_name='decoderbufs.TypeInfo.value_optional', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=330,
  serialized_end=382,
)


_ROWMESSAGE = _descriptor.Descriptor(
  name='RowMessage',
  full_name='decoderbufs.RowMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transaction_id', full_name='decoderbufs.RowMessage.transaction_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='commit_time', full_name='decoderbufs.RowMessage.commit_time', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='table', full_name='decoderbufs.RowMessage.table', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='op', full_name='decoderbufs.RowMessage.op', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='new_tuple', full_name='decoderbufs.RowMessage.new_tuple', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='old_tuple', full_name='decoderbufs.RowMessage.old_tuple', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='new_typeinfo', full_name='decoderbufs.RowMessage.new_typeinfo', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=623,
)

_DATUMMESSAGE.fields_by_name['datum_point'].message_type = _POINT
_DATUMMESSAGE.oneofs_by_name['datum'].fields.append(
  _DATUMMESSAGE.fields_by_name['datum_int32'])
_DATUMMESSAGE.fields_by_name['datum_int32'].containing_oneof = _DATUMMESSAGE.oneofs_by_name['datum']
_DATUMMESSAGE.oneofs_by_name['datum'].fields.append(
  _DATUMMESSAGE.fields_by_name['datum_int64'])
_DATUMMESSAGE.fields_by_name['datum_int64'].containing_oneof = _DATUMMESSAGE.oneofs_by_name['datum']
_DATUMMESSAGE.oneofs_by_name['datum'].fields.append(
  _DATUMMESSAGE.fields_by_name['datum_float'])
_DATUMMESSAGE.fields_by_name['datum_float'].containing_oneof = _DATUMMESSAGE.oneofs_by_name['datum']
_DATUMMESSAGE.oneofs_by_name['datum'].fields.append(
  _DATUMMESSAGE.fields_by_name['datum_double'])
_DATUMMESSAGE.fields_by_name['datum_double'].containing_oneof = _DATUMMESSAGE.oneofs_by_name['datum']
_DATUMMESSAGE.oneofs_by_name['datum'].fields.append(
  _DATUMMESSAGE.fields_by_name['datum_bool'])
_DATUMMESSAGE.fields_by_name['datum_bool'].containing_oneof = _DATUMMESSAGE.oneofs_by_name['datum']
_DATUMMESSAGE.oneofs_by_name['datum'].fields.append(
  _DATUMMESSAGE.fields_by_name['datum_string'])
_DATUMMESSAGE.fields_by_name['datum_string'].containing_oneof = _DATUMMESSAGE.oneofs_by_name['datum']
_DATUMMESSAGE.oneofs_by_name['datum'].fields.append(
  _DATUMMESSAGE.fields_by_name['datum_bytes'])
_DATUMMESSAGE.fields_by_name['datum_bytes'].containing_oneof = _DATUMMESSAGE.oneofs_by_name['datum']
_DATUMMESSAGE.oneofs_by_name['datum'].fields.append(
  _DATUMMESSAGE.fields_by_name['datum_point'])
_DATUMMESSAGE.fields_by_name['datum_point'].containing_oneof = _DATUMMESSAGE.oneofs_by_name['datum']
_ROWMESSAGE.fields_by_name['op'].enum_type = _OP
_ROWMESSAGE.fields_by_name['new_tuple'].message_type = _DATUMMESSAGE
_ROWMESSAGE.fields_by_name['old_tuple'].message_type = _DATUMMESSAGE
_ROWMESSAGE.fields_by_name['new_typeinfo'].message_type = _TYPEINFO
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['DatumMessage'] = _DATUMMESSAGE
DESCRIPTOR.message_types_by_name['TypeInfo'] = _TYPEINFO
DESCRIPTOR.message_types_by_name['RowMessage'] = _ROWMESSAGE
DESCRIPTOR.enum_types_by_name['Op'] = _OP

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), dict(
  DESCRIPTOR = _POINT,
  __module__ = 'msg_pb2'
  # @@protoc_insertion_point(class_scope:decoderbufs.Point)
  ))
_sym_db.RegisterMessage(Point)

DatumMessage = _reflection.GeneratedProtocolMessageType('DatumMessage', (_message.Message,), dict(
  DESCRIPTOR = _DATUMMESSAGE,
  __module__ = 'msg_pb2'
  # @@protoc_insertion_point(class_scope:decoderbufs.DatumMessage)
  ))
_sym_db.RegisterMessage(DatumMessage)

TypeInfo = _reflection.GeneratedProtocolMessageType('TypeInfo', (_message.Message,), dict(
  DESCRIPTOR = _TYPEINFO,
  __module__ = 'msg_pb2'
  # @@protoc_insertion_point(class_scope:decoderbufs.TypeInfo)
  ))
_sym_db.RegisterMessage(TypeInfo)

RowMessage = _reflection.GeneratedProtocolMessageType('RowMessage', (_message.Message,), dict(
  DESCRIPTOR = _ROWMESSAGE,
  __module__ = 'msg_pb2'
  # @@protoc_insertion_point(class_scope:decoderbufs.RowMessage)
  ))
_sym_db.RegisterMessage(RowMessage)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n&io.debezium.connector.postgresql.protoB\007PgProtoH\001'))
# @@protoc_insertion_point(module_scope)
